### ISSUE TITLE
Fan don't turn on after reboot

### ISSUE THREAD

**Issue by DigitalYemeni** [jscoobyced/raspi-utils#1]
Hi there!

First of all I would like think you for this piece of art and excellent work!

I would like to check with you that after installing this on my Raspberry Pi 4, 8Gig RAM, everything went well and i can see the RGB lights changes and the fan turns on every now and then. However, if the CPU goes under stress and I reboot the RPi then it boots straight on a Red color but the Fan is not working until i push it manually then it starts to run.

Can you check if this is a fault in the code logic or my RGB HAT has some hardware issue.

Thank you so much once again!

**Comment by jscoobyced** [comment]
Hi @DigitalYemeni,

Glad you find it useful. It is possible that my code doesn't handle well if the CPU is hot at boot time (I mostly tested when the CPU is cold)
I'll have a look this week and update if needed. Stay posted ;)

**Comment by jscoobyced** [comment]
I had a quick look at the script and at first glance I don't see anything obvious that would give the behavior you describe. But to be thorough, I'll try and reproduce on my RPi (it's a RPI 4 with 4GB, shouldn't have any difference in regard of the RGB HAT).
Also out of curiosity, how did you come across this repo? Google search or GitHub search or any other channel?
Cheers.

**Comment by DigitalYemeni** [comment]
Hi @jscoobyced 
Thanks for your replies! I found your code on google search because when i bought this RGB HAT it supposed to work for RPi based on the Raspian OS. Since i wanted to run my RPi on ubuntu i stumbled for a while and went to search for quick solution especially when my linux skill is not so good! :) then i found someone gave a link to your blog where you put the steps to get it installed and i was more than happy to find it! So thanks a million again :)

I noticed this behaviour because my RPi doesn’t have any heatsink so the CPU went hot quickly and after installation i rebooted and it went straight to red but the fan was not moving until i pushed it. i cooled the CPU until i got the green and blue then it stopped and runs normally when green. i gave it another stress test and rebooted and got the same issue then i thought of asking you hoping you can check by reproducing the behaviour. 

Thank you

**Comment by jscoobyced** [comment]
Hello. I did a quick test and I confirm something is wrong in the code when the RPi starts with temperature above the `TEMP_HIGH` value.
I simply reduced the thresholds to low temperature so it detected the CPU was too hot and started in RED.
I'll have a look at the fix by the end of the week.

Cheers!

**Comment by DigitalYemeni** [comment]
Great! That would make your code prefect then :) 

Thank you so much

**Comment by jscoobyced** [comment]
Hi @DigitalYemeni I have updated the script `cooling.py`
It seems starting the fan at higher speed doesn't work. I need to increase the speed gradually.
Please note that when you boot the LED might turn red before the fan is going to start. Let the system fully load and you should see the fan starting.

**Comment by DigitalYemeni** [comment]
Hi @jscoobyced I have updated the file with your latest code and it seems working well! However, i ran stress test by opening many browser tabs and ran few terminal commands until the cpu got to almost 99% but the temperature did not cross 57C but the fan was running non-stop until i rebooted the RPi and it came up just fine, meaning no red color this time.

Out of curiosity, did you manage to get the cpu hogged until the temperature crossed 57C and got the red color for a while until you stopped the test? which tool did you used to stress the cpu?

Anyways thanks a lot for the great fix!! ;)

**Comment by jscoobyced** [comment]
To test, I changed the threshold (defaults are HIGH/RED=58C, MEDIUM/GREEN=56C and LOW/BLUE=54C) to 52/50/48.
When the LEDs are RED, the fan will spin faster
When the LEDs are GREEN, the fan will spin medium speed
When the LEDs are BLUE, the fan stops.
By changing the values of the thresholds, I could emulate the same behavior as if the CPU is heating. Note I am not checking the CPU load for the LEDs, only the temperature.

It is possible that the CPU reaching 99% killed the cooling script process and the hardware stayed on the last state (i.e. RED / fast spin).
When you reached 99% CPU, what color was the LEDs? If GREEN it is expected for the fan to spin until the CPU cools down to below 54C. Instead of rebooting once you reach 99%, try this command in the terminal to check if the process is still running:
```
sudo systemctl status cooling.service
```
It should show something like this:
![image](https://user-images.githubusercontent.com/19742131/103099334-a715b100-4640-11eb-8a43-ae222c2199de.png)

The `Active` value should be green color and `active (running)`.
If it is not, you can just restart it this way:
```
sudo systemctl start cooling.service
```

**Comment by DigitalYemeni** [comment]
Hi @jscoobyced 
When I reached 99% CPU, the color was green LEDs. I was opening terminal with the “watch sensors” command running to see the cpu temperature and it didn’t go beyond 57C but it goes down sometimes to 52C and get blue LEDs
which means that the script was doing fine and was not killed during the cpu hogging test, or that i presumed, as i didn’t pay attention to the script process to see if it’s still running and getting the sensors reading correctly. I think the watch sensors command is very much matching your LED display readings also and i guess your code is utilising that sensors package to get the temperature status, right?!

Later i will do more tests and let know if i find anything interesting 

Thank you

**Comment by jscoobyced** [comment]
Great, so it seems everything is as expected:
CPU temperature 57C --> LED GREEN, fan spin medium speed
CPU goes down to below 54C --> LED BLUE and fan stops

If you want to adjust the level (my RPi isn't doing high CPU processing) so the BLUE level is triggered at a higher temperature, you can edit the file `/opt/cooling-fan/cooling.py` and change lines 17, 18 and 19) from
```
TEMP_HIGH = 58
TEMP_MEDIUM = 56
TEMP_LOW = 54
```
to
```
TEMP_HIGH = 60
TEMP_MEDIUM = 58
TEMP_LOW = 56
```
or with any value that work for you.
This makes me thinking I might add support for profiles to provide different sets of threshold and make it easier (i.e. without editing code :) )

I would consider this bug solved. I'll close this issue tomorrow (just in case I missed something).

Cheers.

**Comment by jscoobyced** [comment]
One last thing, I just changed the configuration so that it will be RED/YELLOW/BLUE
GREEN is misleading :D

**Comment by DigitalYemeni** [comment]
Perfect! I set my values as:

TEMP_HIGH = 52
TEMP_MEDIUM = 50
TEMP_LOW = 48

That way if the CPU spikes to >98% then i get a red color which means something is using the cpu quite extensively for a long time which means something needs attention! Once the cpu drops to normal % i get the normal yellow/blue colors! :)

It works perfectly now and you can close this issue and consider it fixed.

Thank you so much again and I wish you all the best in your future projects!

**Comment by jscoobyced** [comment]
Thank you for raising it and help contribute to the fix and tests.
